version: "3.9"

networks:
  marketsentinel-net:

volumes:
  redis-data:
  grafana-data:
  prometheus-data:

services:

  ####################################################
  # REDIS (Inference Cache)
  ####################################################
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - marketsentinel-net

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M



  ####################################################
  # API (Inference Engine)
  ####################################################
  api:
    build:
      context: .
      dockerfile: docker/inference.Dockerfile

    restart: unless-stopped
    networks:
      - marketsentinel-net

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/live"]
      interval: 30s
      timeout: 5s
      retries: 3

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 768M



  ####################################################
  # TRAINING (Run Manually)
  ####################################################
  training:
    build:
      context: .
      dockerfile: docker/training.Dockerfile

    networks:
      - marketsentinel-net

    env_file:
      - .env

    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data

    profiles:
      - training

    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G



  ####################################################
  # PROMETHEUS
  ####################################################
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - marketsentinel-net

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    volumes:
      - ./app/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    depends_on:
      - api

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M



  ####################################################
  # GRAFANA
  ####################################################
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - marketsentinel-net

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    env_file:
      - .env

    depends_on:
      - prometheus

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M