version: "3.9"

services:

  # -------------------------------------------------
  # INFERENCE API
  # -------------------------------------------------

  api:
    build:
      context: .
      dockerfile: docker/inference.Dockerfile
    container_name: marketsentinel-api
    ports:
      - "8000:8000"

    volumes:
      - ./artifacts:/app/artifacts

    restart: always
  # -------------------------------------------------
  # PROMETHEUS
  # -------------------------------------------------

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./app/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  # -------------------------------------------------
  # GRAFANA
  # -------------------------------------------------

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
