version: "3.9"

services:

  # -------------------------------------------------
  # REDIS (Prediction Cache)
  # -------------------------------------------------

  redis:
    image: redis:7-alpine
    container_name: marketsentinel-redis
    ports:
      - "6379:6379"
    restart: always


  # -------------------------------------------------
  # BACKGROUND MARKET REFRESHER
  # 🔥 Keeps datasets + features HOT
  # -------------------------------------------------

  market-refresher:
    build:
      context: .
      dockerfile: docker/training.Dockerfile
    container_name: marketsentinel-refresher

    command: >
      python -m training.market_refresher

    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts

    restart: always

    depends_on:
      - redis


  # -------------------------------------------------
  # INFERENCE API
  # -------------------------------------------------

  api:
    build:
      context: .
      dockerfile: docker/inference.Dockerfile
    container_name: marketsentinel-api

    ports:
      - "8000:8000"

    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data   # 🔥 CRITICAL (shared datasets)

    depends_on:
      - redis
      - market-refresher

    restart: always


  # -------------------------------------------------
  # PROMETHEUS
  # -------------------------------------------------

  prometheus:
    image: prom/prometheus
    container_name: prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    volumes:
      - ./app/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    depends_on:
      - api


  # -------------------------------------------------
  # GRAFANA
  # -------------------------------------------------

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus
